repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      - id: ruff-check
        exclude: ".githooks/"
      - id: ruff-format

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
